# Generated by Django 4.2.16 on 2026-09-14 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, verbose_name='用户名')),
                ('action', models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('register', '注册'), ('adduser', '添加用户')], db_index=True, default='login', max_length=32, verbose_name='操作')),
                ('datetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='时间')),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'ordering': ['-datetime', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False, verbose_name='材料编号')),
                ('name', models.CharField(db_column='material_name', max_length=64, unique=True, verbose_name='材料名称')),
                ('info', models.TextField(blank=True, db_column='material_info', default='', verbose_name='材料简介')),
                ('location', models.CharField(blank=True, db_column='material_location', default='', max_length=255, verbose_name='产地')),
                ('count', models.CharField(blank=True, db_column='material_count', default='', max_length=255, verbose_name='库存')),
            ],
            options={
                'verbose_name': '材料',
                'verbose_name_plural': '材料',
                'ordering': ['material_id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('admin', '管理员'), ('user', '普通用户')], default='user', max_length=16, verbose_name='权限')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户权限',
                'verbose_name_plural': '用户权限',
            },
        ),
        migrations.CreateModel(
            name='IdentifyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, verbose_name='操作用户')),
                ('action', models.CharField(choices=[('identify', '识别'), ('feedback', '反馈')], db_index=True, default='identify', max_length=32, verbose_name='操作')),
                ('datetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='时间')),
                ('material_name', models.CharField(blank=True, default='', max_length=64, verbose_name='识别材料')),
                ('material_truename', models.CharField(blank=True, default='', max_length=64, verbose_name='实际材料')),
                ('img_path', models.CharField(blank=True, default='', max_length=255, verbose_name='图片路径')),
                ('confidence', models.CharField(blank=True, default='', max_length=16, verbose_name='置信度')),
                ('confidences', models.JSONField(blank=True, default=dict, verbose_name='全类别置信度')),
                ('corrects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='recognition.identifylog', verbose_name='反馈对应的识别记录')),
            ],
            options={
                'verbose_name': '材料识别日志',
                'verbose_name_plural': '材料识别日志',
                'ordering': ['-datetime', '-id'],
                'indexes': [models.Index(fields=['action', '-datetime'], name='recognition_action_d3bf80_idx')],
            },
        ),
    ]
